[package]
authors.workspace = true
edition.workspace = true
name = "storage-common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.1.0"
xstd = { path = "../xstd" }
