[package]
authors.workspace = true
edition.workspace = true
name = "storage-store"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storage-common = { path = "../common" }
xstd = { path = "../xstd" }
